
environment:
  matrix:
    - nodejs_version: "6.9.1"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g @angular/cli@latest
  - npm install
  
test_script:
  - node --version
  - npm --version
  - npm test -watch false --single-run true

build: off

cache:
  - node_modules
